### PR TITLE
Add datasets_wikidata.csv

### PR DESCRIPTION
**Pull request by pachevalier**
…//github.com/etalab/datagouv-search-indicator/issues/21

I'm not sure of the best strategy : erase the original datasets‧csv or keep two differnt files : one with wikidata and one without.

We go from 49 lines to 121 !

Here is the code which has been used to concatenates files. 
```
library(tidyverse)
read_csv("data/datasets‧csv") %>% 
  bind_rows(., read_csv("data/wikidata_labels‧csv")) %>%
  bind_rows(., read_csv("data/wikidata_alias‧csv")) %>%
  distinct() %>%
  arrange(expected) %>%
  write_csv("data/datasets_wikidata‧csv")

```

### CODE REVIEW

**Comment by abulte** [comment]
I think a `datasets_wikidata.csv` only with wikidata data (sic) is the way to go. We probably don't wan't to mix "human" expectations with "(wiki)data" ones, and appending both input files while running the script (if we want to) will be easy.

**Comment by pachevalier** [comment]
Ok, new datasets with 76 lines.

**Comment by abulte** [comment]
Can you replace NA with ``? 😇

**Comment by abulte** [comment]
🎉 🙏

**Comment by abulte** [comment]
`  bind_rows(., read_csv("data/wikidata_labels‧csv")) %>%`

Y'a vraiment des points médians en R ? 🤯

**Comment by pachevalier** [comment]
Non c'est l'extension "écriture inclusive" de firefox. à désactiver ;)

**Pull request merged**
